name: EssentialZ
version: '${project.version}'
main: com.zetaplugins.essentialz.EssentialZ
api-version: '1.21'
load: STARTUP
authors: [ Kartoffelchipss ]
description: A modern essentials plugin for Minecraft
website: https://strassburger.org

softdepend:
  - PlaceholderAPI

commands:
  essentialz:
    description: Main command for EssentialZ
    aliases:
      - esz

permissions:
  essentialz.playtime:
    default: true
    description: Allows the user to see the playtime of a player
  essentialz.skull:
    default: op
    description: Allows the user to get the skull of a player
  essentialz.itemname:
    default: op
    description: Allows the user to change the name of an item
  essentialz.itemlore:
    default: op
    description: Allows the user to change the lore of an item
  essentialz.fly:
    default: op
    description: Allows the user to fly
  essentialz.fly.others:
    default: op
    description: Allows the user to give other players flight
  essentialz.flyspeed:
    default: op
    description: Allows the user to change the fly speed of a player
  essentialz.flyspeed.others:
    default: op
    description: Allows the user to change the fly speed of other players
  essentialz.walkspeed:
    default: op
    description: Allows the user to change the walk speed of a player
  essentialz.walkspeed.others:
    default: op
    description: Allows the user to change the walk speed of other players
  essentialz.gamemode:
    default: op
    description: Allows the user to change the gamemode of a player
  essentialz.gamemode.others:
    default: op
    description: Allows the user to change the gamemode of other players
  essentialz.godmode:
    default: op
    description: Allows the user to enable godmode
  essentialz.godmode.others:
    default: op
    description: Allows the user to enable godmode for other players
  essentialz.clearchat:
    default: op
    description: Allows the user to clear the chat
  essentialz.give:
    default: op
    description: Allows the user to give items to players
  essentialz.msg:
    default: true
    description: Allows the user to send private messages to other players
  essentialz.msg.color:
    default: op
    description: Allows the user to use colors in private messages
  essentialz.msg.toggle:
    default: true
    description: Allows the user to toggle private messages on or off
  essentialz.teamchat:
    default: op
    description: Allows the user to use team chat
  essentialz.teamchat.color:
    default: op
    description: Allows the user to use colors in team chat
  essentialz.broadcast:
    default: op
    description: Allows the user to broadcast messages to the server
