name: EssentialZ
version: '${project.version}'
main: org.strassburger.essentialz.EssentialZ
api-version: '1.21'
load: STARTUP
authors: [ Kartoffelchipss ]
description: A modern essentials plugin for Minecraft
website: https://strassburger.org

softdepend:
  - PlaceholderAPI

commands:
  essentialz:
    description: Main command for EssentialZ
    aliases:
      - esz
  playtime:
    description: Get the playtime of a player
    permission: essentialz.playtime
  skull:
    description: Get the skull of a player
    permission: essentialz.skull
  itemname:
    description: change the name of an item
    permission: essentialz.itemname
  itemlore:
    description: change the lore of an item
    permission: essentialz.itemlore
    aliases:
      - lore
  fly:
    description: Allow the player to fly
    permission: essentialz.fly
  flyspeed:
    description: Change the fly speed of a player
    permission: essentialz.flyspeed
  walkspeed:
    description: Change the walk speed of a player
    permission: essentialz.walkspeed
    aliases:
      - speed
  gmc:
    description: Change the gamemode of a player to creative
    permission: essentialz.gamemode
  gms:
    description: Change the gamemode of a player to survival
    permission: essentialz.gamemode
  gma:
    description: Change the gamemode of a player to adventure
    permission: essentialz.gamemode
  gmsp:
    description: Change the gamemode of a player to spectator
    permission: essentialz.gamemode
  gamemode:
    description: Change the gamemode of a player
    permission: essentialz.gamemode
    aliases:
      - gm

permissions:
  essentialz.playtime:
    default: true
    description: Allows the user to see the playtime of a player
  essentialz.skull:
    default: op
    description: Allows the user to get the skull of a player
  essentialz.itemname:
    default: op
    description: Allows the user to change the name of an item
  essentialz.itemlore:
    default: op
    description: Allows the user to change the lore of an item
  essentialz.fly:
    default: op
    description: Allows the user to fly
  essentialz.fly.others:
    default: op
    description: Allows the user to give other players flight
  essentialz.flyspeed:
    default: op
    description: Allows the user to change the fly speed of a player
  essentialz.flyspeed.others:
    default: op
    description: Allows the user to change the fly speed of other players
  essentialz.walkspeed:
    default: op
    description: Allows the user to change the walk speed of a player
  essentialz.walkspeed.others:
    default: op
    description: Allows the user to change the walk speed of other players
  essentialz.gamemode:
    default: op
    description: Allows the user to change the gamemode of a player
  essentialz.gamemode.others:
    default: op
    description: Allows the user to change the gamemode of other players
