name: EssentialZ
version: '${project.version}'
main: com.zetaplugins.essentialz.EssentialZ
api-version: '1.21'
load: STARTUP
authors: [ Kartoffelchipss ]
description: A modern essentials plugin for Minecraft
website: https://strassburger.org

softdepend:
  - PlaceholderAPI
  - Vault
  - floodgate
